### ISSUE TITLE
Not able to find .env file in any directory

### ISSUE THREAD

**Issue by brajbhushan-tripathi** [drivendata/cookiecutter-data-science#178] opened 2019-08-07 11:47 UTC
Hi,

I think there used to be a .env file in the folder structure which I am not able to find anywhere. Please help.

Thanks,
Brajbhushan

**Comment by pjbull** [comment] 2019-08-07 15:21
`.env` is created in all projects, as you can see here:
https://github.com/drivendata/cookiecutter-data-science/tree/master/%7B%7B%20cookiecutter.repo_name%20%7D%7D

On some OSes, this will be a hidden file because it starts with `.`. If you are on a unix system, listing the directory with `ls -a` will show all files (including hidden ones).

Closing, not a bug.

**Closed by pjbull** 2019-08-07 15:21 UTC

**Comment by brajbhushan-tripathi** [comment] 2019-08-08 11:11
It wasn't created the first time, but I tried again and it worked. Thanks for the response!
