### ISSUE TITLE
Option to Snakemake file instead of Makefile

### ISSUE THREAD

**Issue by ghltshubh** [drivendata/cookiecutter-data-science#263] opened 2022-03-11 16:29 UTC
[Snakemake](https://snakemake.readthedocs.io/en/stable/) is more pythonic and suitable for python projects since it is developed by python practitioners who also happened to use make so they know the shortcomings of make.

**Comment by pjbull** [comment] 2022-03-11 20:37
dupe of https://github.com/drivendata/cookiecutter-data-science/issues/9

**Closed by pjbull** 2022-03-11 20:37 UTC
