### ISSUE TITLE
Integration with dvc

### ISSUE THREAD

**Issue by shcheklein** [drivendata/cookiecutter-data-science#158] opened 2019-01-27 07:26 UTC
Adding [DVC](https://dvc.org) support can benefit this framework in two ways:

1. Provide version control backend for data files - including intermediate results, models, etc. As you know git is not the best solution for storing data files. Storing and versioning data is crucial for reproducibility.
2. Serve as an easier (to learn) alternative to makefiles. DVC allows for tracking execution steps, dependencies between them, etc. All from CLI, no need to learn a new language (make).

I think both projects can benefit and get more visibility from this. Let me know what you think.

**Comment by isms** [comment] 2019-01-29 17:47
Our approach to integrations is generally to leave that up to the user.

Some questions that might be helpful to hear more about:
* If somebody intending to use DVC can just `dvc init` in their project then what would an integration look like?
* And if they don't use or know about DVC is the purpose of the integration to push them to use it or educate about its merits? How might this affect the user experience?

**Comment by shcheklein** [comment] 2019-02-07 03:11
@isms good questions!

I've prepared a PR https://github.com/drivendata/cookiecutter-data-science/pull/159 to show how the first step would look like. Would be great to learn what you think.

In data science projects it's as important to version control data as versioning source code. The current version of the framework does some job already with `aws sync`, but it's not flexible and flawed in a lot of scenarios:

1. Data does not have versions (maybe you can utilize some AWS S3 magic, I don't know? but even that would be painful, see 2)
2. It's not connected to your code. It's hard to find what specific data was used to train a certain model. It's actually pretty hard to get a certain model in the first place (let's say, using git tags, for example).
3. It breaks the collaboration - if multiple people write to the same bucket.
4. The current approach is not flexible. Only S3 is supported. I know that this framework is opinionated. But maybe it makes sense to provide support for SSH, GC, Azure at least?

In my PR, I'm trying to solve the first 3 points w/o breaking UI/UX:

* the set of commands to sync data stays the same
* DVC can be initialized optionally
* If it's initialized takes care of syncing data instead of `aws sync` under the hood. Thus enabling proper versioning (via `data.dvc` file).

<img width="663" alt="screen shot 2019-02-06 at 6 52 06 pm" src="https://user-images.githubusercontent.com/3659196/52387830-88a06f80-2a40-11e9-8d4a-4f7848a499f5.png">

<img width="607" alt="screen shot 2019-02-06 at 6 54 32 pm" src="https://user-images.githubusercontent.com/3659196/52387861-aff73c80-2a40-11e9-970a-2c057262a0ff.png">

(`initialize_version_control` runs automatically once when you do `make data`)

Please, let me know what you think about this and if you have any questions! Looking forward to discussing this.

**Comment by isms** [comment] 2019-02-10 15:37
Hey @shcheklein, thanks for the thoughtful response and the PR (#159). It's awesome to see another project designed to help keep projects organized and reproducible, and for the record I think DVC addresses a major pain point and should be seriously considered for all data projects.

I think this proposal ties into a larger conversation where we are struggling to find the right balance between what we might call the "Rails philosophy" and the Unix philosophy for Cookiecutter Data Science.

### The Rails philosophy

Rails' creator like to say that "[Rails is omakase](https://dhh.dk/2012/rails-is-omakase.html)," a reference to sushi orders where the chef chooses everything for you. Rails makes a ton of design choices about different technologies and if you don't like it then, y'know, tough, don't use it.

If this project were more like Rails, we actually wouldn't have any configuration options — we would just set up all the things we believe users _should_ be doing, like using DVC.

### The Unix philosophy

On the other side of the spectrum, the Unix philosophy emphasizes small, focused, simple tools that do one thing well but compose nicely with other small, focused, simple programs.

If this project were more in line with the Unix philosophy we would not have many options at all, because we would (for example) decline to interact with the user's requirements or virtualenv at all as a violation of separation of concerns. We'd also not even have our S3 shortcuts because stashing data is a separate concern, S3 isn't the only data storage out there, and why reinvent the wheel?

### Applying the logic here

If a given user is already familiar with DVC, it's a `dvc init` away. We don't automatically run `git init` either because that's not the value proposition of this project.

If a given user is not familiar with DVC, the option exists I suppose to push them to learn more about it and use it?

There's a world in which we embrace that and don't even ask whether the user wants to use DVC, we just decide that everybody should be using DVC and initialize it without asking. That is Rails-y. There's also a world in which we don't initialize DVC and don't even ask because honestly it's a different tool and DVC is not the only option out there.

My concern with the Rails way of imposing "best practices" is pretty simple: most people don't already use DVC, don't know how it works, and so it would be yet another scary learning curve getting in the way of people adopting this project (and thereby hopefully improving data practices).
 
But you're proposing an option rather than a rule so let's address that instead of a strawman.

I am still not sure whether we want to use options to push users to use things they are not already familiar with, so I guess I just want to be clear on whether the goal of this issue/PR is to push the adoption of DVC by referencing it in this project or whether there is something I am missing that the integration does above and beyond evangelizing?

(By the way, that's not a trick question  because as discussed above it can a valid approach to nudge people in the right direction a la Rails.)

### Why bother with the philosophizing? Why not just add it?

The downside of options is that they add complexity. But that's a little handwavy so let's bring it back to concrete concerns: each boolean option is a forking path that slices the user base and doubles the number of permutations to debug and keep working.

This project has a philosophy of [being conservative](https://drivendata.github.io/cookiecutter-data-science/#be-conservative-in-changing-the-default-folder-structure) about changes that affect everyone while adopting a Unix-y attitude toward how people compose this tool with other tools.

I just want to make sure we are being thoughtful here and in many other issues which I could easily copy this (long) blurb into.

Maybe it's time to create a 'cookiecutter enhancement proposal' template like [Python PEP](https://www.python.org/dev/peps/)s or [Rust RFCs](https://github.com/rust-lang/rfcs) where—anytime somebody wants to make a chance that affects everybody rather than a simple bugfix—there is a standard set of design and implementation questions to answer which the community can then knowledgeably discuss.

Thoughs @shcheklein, @dmpetrov, and @pjbull?

**Comment by bon** [comment] 2019-02-10 16:28
Yesterday I asked on the `dvc` discord discussion whether anyone had thought about combining `dvc` and `cookiecutter-data-science` and I got pointed to this discussion. I guess it was a timely question.

We have adapted `cookiecutter-data-science` to our purposes, whipping out a few things and adding others so I'm going to give this PR a try to see how well it fits.

What I would actually like to see is a further integration of the two where the dependencies are kept in the `Makefile`s and not in the `.dvc` files. `dvc` would then read this dependency information and act on it. 

Potential advantages are that `make` is tried and tested as well as being much more expressive than the `.dvc` DSL.

I'd be curious to hear others' thoughts on this.

**Comment by shcheklein** [comment] 2019-02-13 01:11
Thanks @isms ! Really great and thoughtful answer! I should have made this PR even for the sake of this discussion :)

Let me try to address certain points in your answer.

> Unix vs Rails

It didn't even come to mind that you were thinking about Unix philosophy, to be honest. This project is already pretty opinionated and like you mentioned is taking care about many things. So, yes, I was thinking more in lines with Rails philosophy. I'm not sure if integrating DVC as it's done in this PR follows Rails philosophy though. Ideally, there should be a way to plug any data storage you want (and have a single common interface to sync data). But it's probably would be too much to expect from the `cookieccutter-*` project. I don't know.

> so I guess I just want to be clear on whether the goal of this issue/PR is to push the adoption of DVC by referencing it in this project or whether there is something I am missing that the integration does above and beyond evangelizing?

That's absolutely true. Evangelizing DVC was not a single or a primary goal though. There were other things to consider:

* First, like I mentioned, the current way of managing data is flawed. I don't even know how do you actually manage to deal with it when you share a single bucket for a team. Or may be I don't know well enough your users, so we overestimated the problem in the first place. It would be helpful if you can get more clarify on this.
* I think there should be a way to support (via DVC or not) at least GC and SSH. I'm not sure about the reasoning behind leaving this to some third-party fork.
* Evangelization is not single-sider in this case. I think evangelizing will help growing both products. Maybe 1 + 1 can give us 10 eventually? Who knows. We would recommend it as an entry point everywhere.
* We made this PR in part because we were thinking about providing a simple entry point for our users. If we go with our own fork it will be cannibalization of this repository to some extent. 

I totally understand you being conservative, though, and we'll be totally fine with either decision on your end.

**Comment by isms** [comment] 2019-10-25 17:19
Closing this in favor of conservation solutions that are not unique to a niche set of tools, but appreciate the thoughtful engagement.

**Closed by isms** 2019-10-25 17:19 UTC
